algorithm:
    name: "???"

    num_classes: "???"

    # optimizer设置
    optimizer:
        name: "???"
        params:
            lr: 0.001

    # scheduler设置
    scheduler:
        name: "???"
        params:
            last_epoch: -1

data:
    root: "./data"
    dataset_using: "???"
    available_datasets:
        voc:
            mean: [0.4573, 0.4373, 0.4045]
            std: [0.2675, 0.2643, 0.2780]
            classnames:
                - aeroplane
                - bicycle
                - bird
                - boat
                - bottle
                - bus
                - car
                - cat
                - chair
                - cow
                - diningtable
                - dog
                - horse
                - motorbike
                - person
                - pottedplant
                - sheep
                - sofa
                - train
                - tvmonitor
        coco:
            mean: [0.4712, 0.4474, 0.4077]
            std: [0.2700, 0.2655, 0.2808]
            classnames:
                - person
                - bicycle
                - car
                - motorbike
                - aeroplane
                - bus
                - train
                - truck
                - boat
                - traffic light
                - fire hydrant
                - stop sign
                - parking meter
                - bench
                - bird
                - cat
                - dog
                - horse
                - sheep
                - cow
                - elephant
                - bear
                - zebra
                - giraffe
                - backpack
                - umbrella
                - handbag
                - tie
                - suitcase
                - frisbee
                - skis
                - snowboard
                - sports ball
                - kite
                - baseball bat
                - baseball glove
                - skateboard
                - surfboard
                - tennis racket
                - bottle
                - wine glass
                - cup
                - fork
                - knife
                - spoon
                - bowl
                - banana
                - apple
                - sandwich
                - orange
                - broccoli
                - carrot
                - hot dog
                - pizza
                - donut
                - cake
                - chair
                - sofa
                - pottedplant
                - bed
                - diningtable
                - toilet
                - tvmonitor
                - laptop
                - mouse
                - remote
                - keyboard
                - cell phone
                - microwave
                - oven
                - toaster
                - sink
                - refrigerator
                - book
                - clock
                - vase
                - scissors
                - teddy bear
                - hair drier
                - toothbrush

    dtype: "float32"

val:
    # dataloader设置
    dataloader:
        shuffle: false
        num_workers: 4
        batch_size: 32
        pin_memory: true
    # 数据增强设置
    transform:
        - name: "ToTensor"
        - name: "Resize"
          params:
              size: [224, 224]
        - name: "Normalize"
          params:
              mean: [0.4573, 0.4373, 0.4045]
              std: [0.2675, 0.2643, 0.2780]

# checkpoint设置
checkpoint:
    save_every: 10
    load_file: null
    save_checkpoint: true
    with_weight_normalization: "???"

train:
    seed: 1024
    epochs: 200
    log_interval: 20
    # dataloader设置
    dataloader:
        shuffle: true
        num_workers: 4
        batch_size: 32
        pin_memory: true
    # 数据增强设置
    transform:
        - name: "ToTensor"
        - name: "RandomResizedCrop"
          params:
              size: [224, 224]
        - name: "RandomHorizontalFlip"
          params:
              p: 0.5
        - name: "ColorJitter"
          params:
              brightness: 0.2
              contrast: 0.2
              saturation: 0.2
              hue: 0.1
        - name: "Normalize"
          params:
              mean: [0.4573, 0.4373, 0.4045]
              std: [0.2675, 0.2643, 0.2780]
