_defaults_:
    - base.yaml

data:
    dataset_using: "voc"

algorithm:
    name: "ExCEL"
    backbone: "resnet101"

    # 优化器
    optimizer:
        name: "AdamW"
        params:
            lr: 0.0001
            weight_decay: 0.02

    scheduler: null

    # 超参数
    # 参考 4.1. Experimental Settings, Implementation Details.
    num_descriptors: 20
    num_attribute_embeddings:
        voc: 112
        coco: 224

    svc_conducted_from_last: 5

    scaling_factor: 3.0
    shifting_factor: 1.0

    loss_weight_gamma: 0.1
