_defaults_:
    - base.yaml

data:
    dataset_using: "voc"

algorithm:
    name: "ExCEL"
    backbone: "ViT-B/32"

    # 优化器
    optimizer:
        name: "AdamW"
        params:
            lr: 0.0001
            weight_decay: 0.02

    scheduler: null

    # 超参数
    # 参考 4.1. Experimental Settings, Implementation Details.
    num_descriptions: 20
    num_attribute_embeddings:
        voc: 112
        coco: 224

    svc_conducted_from_last: 5

    scaling_factor: 3.0
    shifting_factor: 1.0

    loss_weight_gamma: 0.1

train:
    epochs: 200
    transform:
        - name: "ToTensor"
        - name: "Resize"
          params:
              # ExCEL使用了CLIP的Visual Encoder
              # 所以数据增强必须要和CLIP一致
              size: [224, 224]
        - name: "Normalize"
          params:
              # mean和std用自己的, 因为都是放缩到-1~1的分布
              mean: [0.4573, 0.4373, 0.4045]
              std: [0.2675, 0.2643, 0.2780]

val:
    transform:
        - name: "ToTensor"
        - name: "Resize"
          params:
              size: [224, 224]
        - name: "Normalize"
          params:
              mean: [0.4573, 0.4373, 0.4045]
              std: [0.2675, 0.2643, 0.2780]
