_defaults_:
    - base.yaml

data:
    dataset_using: "voc"

algorithm:
    name: "PSA"
    # Multi-Label Classification网络
    classification_backbone: "resnet34"
    classification_pretrained: true

    # AffinityNet 网络
    affinity_weight_path: null

    # Segmentation 网络
    segmentation_backbone: "deeplab"
    segmentation_weight_path: null

    alpha_weaken: 24
    alpha_amplify: 4
    alpha_default: 16

    gamma: 5

    beta: 8

    t: 256

    # 优化器
    optimizer:
        name: "Adam"
        params:
            lr: 1e-3
            weight_decay: 0.01

    scheduler:
        name: null

    # 超参数
