_defaults_:
    - base.yaml

data:
    dataset_using: "voc"
    available_datasets:
        voc:
            background:
                - "ground"
                - "land"
                - "grass"
                - "tree"
                - "building"
                - "wall"
                - "sky"
                - "lake"
                - "water"
                - "river"
                - "sea"
                - "railway"
                - "railroad"
                - "keyboard"
                - "helmet"
                - "cloud"
                - "house"
                - "mountain"
                - "ocean"
                - "road"
                - "rock"
                - "street"
                - "valley"
                - "bridge"
                - "sign"
        coco:
            background:
                - "ground"
                - "land"
                - "grass"
                - "tree"
                - "building"
                - "wall"
                - "sky"
                - "lake"
                - "water"
                - "river"
                - "sea"
                - "railway"
                - "railroad"
                - "keyboard"
                - "helmet"
                - "cloud"
                - "house"
                - "mountain"
                - "ocean"
                - "road"
                - "rock"
                - "street"
                - "valley"
                - "bridge"

algorithm:
    name: "PSA"
    backbone: "ViT-B/16"
    feature_dim: 256
    in_channels: 3
    out_channels: 512
    num_classes: 21

    n0: 6
    alpha: 2
    lambda_affinity: 0.1

    prompt: "a clean origami [CLS]."

    # 优化器
    optimizer:
        name: "AdamW"
        params:
            lr: 6e-5
            weight_decay: 0.01

    scheduler:
        name: null

    # 超参数
